import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Footer from "@/app/components/footer";
import DebugInfo from "@/app/components/debugInfo";
import LinkButton from "@/app/components/linkButton";
import CheckBoxButton from "@/app/components/checkBox";

export const metadata: Metadata = {
  title: "Voir Montcuq",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
    <body className="h-full w-full">
    <DebugInfo/>
    <ul className={"group flex flex-col w-fit h-fit p-2 bg-secondary-600/75 m-1.5 text-secondary-50 rounded-md self-end backdrop-blur-md z-[60] absolute left-0 md:top-0 top-1/4"}>
      <li className={"md:hidden"}><img src={"/icons/SVG/options.svg"} className={"h-11 w-10 inline"}/></li>
      <li className={"p-1 my-2 md:inline hidden group-hover:inline"}><LinkButton href={"/"}>Acceuil</LinkButton></li>
      <li className={"p-1 my-2 md:inline hidden group-hover:inline"}></li>
      <li className={"p-1 my-2 group md:inline hidden group-hover:inline"}><pre>Accessibilité</pre></li>
      <li className={" md:inline hidden group-hover:inline"}><CheckBoxButton id={"reduces-motion"} className = {" bg-secondary-600 text-primary-50 p-2.5 pr-4 pl-4 rounded border border-secondary-300"}>Animation</CheckBoxButton>
      </li>
    </ul>
    {children}
    <Footer/>
    </body>
    </html>
  );
}
